apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplenodeapp-deployment
spec:
  selector:
    matchLabels:
      app: samplenodeapp
      type: api
  replicas: 1 
  template:
    metadata:
      labels:
        app: samplenodeapp
        type: api
    spec:
      containers:
      - name: samplenodeapp-container
        image: sankardockerdev/node-web-app
        ports:
        - containerPort: 3000
        env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
  labels:
    app: api-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: samplenodeapp
    type: api
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc
